org.gradle.jvmargs=-Xmx2G --enable-native-access=ALL-UNNAMED
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17.17

# Mod Properties
mod_version=v3.0.0
maven_group=com.helium
archives_base_name=helium

# Dependencies
fabric_api_version=0.155.2+26.1.2
cloth_config_version=26.1.154
modmenu_version=18.0.0
sodium_api_version=0.9.1+mc26.1.2
