org.gradle.jvmargs=-Xmx2G --enable-native-access=ALL-UNNAMED
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric / Minecraft
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17.20

# Mod Properties
mod_version=v3.0.0
maven_group=com.helium
archives_base_name=helium

# Dependencies
fabric_api_version=0.160.0+26.2
cloth_config_version=26.2.155
modmenu_version=20.0.1
sodium_api_version=0.9.1+mc26.2
sodium_version=mc26.2-0.9.1-fabric
